services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  user-service:
    build: ./user
    container_name: user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  captain-service:
    build: ./captain
    container_name: captain-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  ride-service:
    build: ./ride
    container_name: ride-service
    ports:
        - "3003:3003"
    depends_on:
        - mongo
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - captain-service
      - ride-service
volumes:
  mongo-data:
    